### ISSUE TITLE
LocalStorage breaks when surfing in private mode in Safari on iOS

### ISSUE THREAD

**Issue by PaRoxUs** [julien-maurel/js-storage#3]
If you surf in private mode in Safari on iOS the js-storage fails because there is no storage_available or localCookieStorage.

http://stackoverflow.com/questions/30048009/html5-localstorage-setitem-is-not-working-on-ios-8-safari-mobile

**Comment by julien-maurel** [comment]
I can't test on iOS. WHen you have the error?  When js-storage is loaded or when you call some methods?

**Comment by Kobe** [comment]
It breaks in macOS Safari too because they have the same behavior.
